# Application
spring.application.name=authenctication

# Server
server.port=8080

# DataSource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5444/authentication_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# OAuth2 Authorization Server
spring.security.oauth2.authorizationserver.issuer=http://localhost:8080

# JWT (for signin API)
app.jwt.access-ttl-seconds=3600
