#!/bin/bash
# Test WebSocket connection from emulator

echo "=== WebSocket Connection Test ==="
echo ""

# Test 1: Can we reach the backend HTTP endpoint?
echo "1️⃣  Testing HTTP connectivity (from emulator):"
echo "   Command: adb shell curl -v http://10.0.2.2:8080/ws/info"
echo ""
echo "   If this FAILS:"
echo "   ❌ Emulator cannot reach backend"
echo "   ❌ Check: Is backend running on port 8080?"
echo "   ❌ Check: Firewall not blocking port 8080"
echo ""
echo "   If this SUCCEEDS:"
echo "   ✅ Network connectivity is OK"
echo "   ✅ Backend is reachable"
echo ""

# Test 2: Can we establish WebSocket?
echo "2️⃣  Testing WebSocket connection (from local machine):"
echo "   Command: wscat -c ws://localhost:8080/ws"
echo ""
echo "   If this FAILS:"
echo "   ❌ WebSocket endpoint may not be properly configured"
echo "   ❌ Check: Is SockJS enabled?"
echo "   ❌ Check: WebSocket security filter"
echo ""
echo "   If this SUCCEEDS:"
echo "   ✅ WebSocket handshake works"
echo "   ✅ Can now test with auth token"
echo ""

# Test 3: WebSocket with authentication
echo "3️⃣  Testing WebSocket with JWT token:"
echo "   Command: wscat -c ws://localhost:8080/ws \\"
echo "            -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "   If this FAILS after connecting:"
echo "   ❌ JWT validation is failing"
echo "   ❌ Check: Backend JWT validation logic"
echo "   ❌ Check: Token expiration"
echo ""
echo "   If this SUCCEEDS:"
echo "   ✅ Authentication is working"
echo "   ✅ Mobile app should also connect"
echo ""

# Test 4: Send test message via STOMP
echo "4️⃣  Sending test message via STOMP:"
echo "   After connecting in wscat, send:"
echo ""
echo "   SUBSCRIBE"
echo "   destination:/user/john.doe/queue/notifications"
echo "   id:sub-1"
echo "   ack:auto"
echo "   "
echo ""
echo "   Then from another terminal, publish to backend"
echo ""

# Test 5: Check backend configuration
echo "5️⃣  Verify Spring Boot configuration:"
echo ""
echo "   Look for in your Spring Boot server logs:"
echo "   - 'Registered message handler' for WebSocket"
echo "   - 'STOMP CONNECT' messages"
echo "   - JWT validation happening"
echo ""
echo "   Common issues in logs:"
echo "   ❌ 'STOMP CONNECT failed' - Auth issue"
echo "   ❌ 'No principal set' - Missing JWT validation"
echo "   ❌ 'Destination not found' - Wrong subscription path"
echo ""

echo ""
echo "=== Quick Start ==="
echo ""
echo "1. Run backend:"
echo "   ./mvnw spring-boot:run"
echo ""
echo "2. Test HTTP endpoint:"
echo "   curl http://localhost:8080/ws/info"
echo ""
echo "3. Test WebSocket (if wscat not installed: npm install -g wscat):"
echo "   wscat -c ws://localhost:8080/ws"
echo ""
echo "4. In another terminal, run mobile app:"
echo "   flutter run --debug"
echo ""
echo "5. Check logs for [STOMP] messages"
echo "   flutter logs | grep STOMP"
echo ""

