package com.hr.referentiel.domain;

public enum ActionWorkflowFormation {
	CREATION_DEMANDE,
	SOUMISE_A_RH,
	VALIDATION_RRH,
	REFUS_RRH,
	INTEGRATION_PLAN,
	ANNULATION_DEMANDEUR,
	NOTIFICATION_ENVOYEE,
	EVALUATION_CHAUDE_ENVOYEE,
	EVALUATION_CHAUDE_RECUE,
	EVALUATION_FROIDE_ENVOYEE,
	EVALUATION_FROIDE_RECUE,
	FORMATION_TERMINEE
}
