# Application
spring.application.name=svc-identite-acces

# Server
server.port=8081

# DataSource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5444/authentication_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# OAuth2 Authorization Server (URL vue par les clients = passerelle)
spring.security.oauth2.authorizationserver.issuer=http://localhost:8080

# JWT (for signin API)
app.jwt.access-ttl-seconds=3600

# Shared token for internal service-to-service endpoints.
# Override this value in each environment.
app.internal-api.token=change-me-internal-token

# Kafka (création de comptes depuis svc-referentiel-rh). Commenter pour désactiver le consumer.
spring.kafka.bootstrap-servers=127.0.0.1:9092

# Courriel : identifiants mobile après création de compte (Kafka). Activer + configurer SMTP en prod.
app.mail.collaborateur-welcome-enabled=true
app.mail.from=no-reply@rh.local
# spring.mail.host=smtp.example.com
# spring.mail.port=587
# spring.mail.username=
# spring.mail.password=
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true


spring.mail.host=127.0.0.1
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
